export const API_CONFIG = {
  URL: 'https://api.themoviedb.org/3',
  KEY: '?api_key=2fff9f8ef7c6cf9ceee1670f42542477',
  QUERY: '&query=',
  PAGE: '&page=',
  FIRST_PAGE: '&page=1',
  SEARCH_LIST: '/search/multi',
  KEYWORDS_LIST: '/search/keyword',
  URL_SIMILAR: '/similar',
  URL_VIDEO: '/videos',
  URL_PEOPLE: '/credits',
  URL_KEYWORDS: '/keywords',
  DISCOVER_MOVIES: '/discover/movie',
  DISCOVER_TVS: '/discover/tv',
  MOVIES_POPULAR: '/movie/popular',
  MOVIES_GENRES: '/genre/movie/list',
  TVS_POPULAR: '/tv/popular',
  TVS_GENRES: '/genre/tv/list',
  PEOPLE_POPULAR: '/person/popular',
  PERSON_WORKS: '/combined_credits',
};
